# Generated by Django 5.2.7 on 2025-10-31 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackerapp',
            old_name='categorizes',
            new_name='category',
        ),
    ]
